server:
  port : 5000
spring:
  datasource:
    url: jdbc:postgresql://tavern-db.cpaphihk7gxr.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=establishment
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  oauth2:
    resource:
      jwk:
        keySetUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_GHe36mnNB/.well-known/jwks.json
    client:
      clientId: 4j0f1t1banedq1jk43nhit3sou
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
app:
  baseUrl: https://master.dmmolrtqzj6oc.amplifyapp.com/
  hash:
    salt: salty