server:
  port: 8088
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
auto:
  create:
    topics:
      enable: true

security:
  oauth2:
    resource:
      jwk:
        keySetUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_dCI229nTx/.well-known/jwks.json
    client:
      clientId: t3mpo80ueani42ktgf2o2crj
feign:
  oauth2:
    enabled: true
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
app:
  backofficeUrl: http://localhost:3000
  hash:
    salt: salty
  clients:
    establishment:
      url: http://localhost:8081