quarkus:
  http:
    port: 8081
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/establishment
  hibernate-orm:
    database:
      generation: update # drop-and-create
    log:
      sql: true
  oidc:
    auth-server-url: http://localhost:8001/auth/realms/bar
    client-id: backend
    credentials:
      secret: b7ac1366-c7e0-4125-87a0-758345aaa447
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: true
