quarkus:
  http:
    port: 8081
    cors:
      ~: true
      methods: GET,PUT,POST
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/establishment
  hibernate-orm:
    database:
      generation: update # drop-and-create
    log:
      sql: true
  oidc:
    auth-server-url: http://localhost:8001/auth/realms/edgy
    client-id: backend
    credentials:
      secret: ed992a9c-331c-4ac6-82fc-4f06bdee95ea
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: true
